# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
#Solution
import numpy as np
ar = np.arange(10,26)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
# Solution
ar1 = np.arange(1,50,2)
print(ar1)
print('the length of the array is -', len(ar1))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
the length of the array is - 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
# Solution
#np.random.seed(27)
ar2 = np.arange(4,7,3/27)
print(ar2)
len(ar2)


[4.         4.11111111 4.22222222 4.33333333 4.44444444 4.55555556
 4.66666667 4.77777778 4.88888889 5.         5.11111111 5.22222222
 5.33333333 5.44444444 5.55555556 5.66666667 5.77777778 5.88888889
 6.         6.11111111 6.22222222 6.33333333 6.44444444 6.55555556
 6.66666667 6.77777778 6.88888889]


27

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [5]:
# Solution
ar3 = np.random.rand(5,4)
ar3
np.round(ar3,2)

array([[0.51, 0.56, 0.08, 0.62],
       [0.17, 0.15, 0.53, 0.5 ],
       [0.16, 0.81, 0.03, 0.69],
       [0.02, 0.12, 0.11, 0.24],
       [0.8 , 0.68, 0.54, 0.44]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [6]:
# Solution
ar4 = np.random.randint(5,15,(5,5))
ar4

array([[11, 11, 13,  7, 12],
       [ 5, 14, 10,  7,  9],
       [ 5,  6, 11,  6, 12],
       [13, 14,  9, 14, 10],
       [13, 10,  7, 12, 12]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [7]:
# Solution
ar5 = np.zeros(19,int)
print(ar5)
print(len(ar5))
print(ar5.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
19
int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [8]:
# Solution
ar6 = np.random.randint(1,2,(2,3))
flt = np.array([ar6],dtype=np.float32)
print(flt)
print(flt.dtype)


[[[1. 1. 1.]
  [1. 1. 1.]]]
float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
# Solution
a1 = np.array([9,25,50,34,45])
a2 = np.array([3,34,34,65,2])
a3 = np.array([5,7,3,76,3])
a4 = np.array([7,8,6,54,6])
a5 = np.array([23,12,8,5,8])
a1 = a1.reshape(1,5)
a2 = a2.reshape(1,5)
a3 = a3.reshape(1,5)
a4 = a4.reshape(1,5)
a5 = a5.reshape(1,5)
ar7 = np.concatenate((a1,a2,a3,a4,a5),axis = 0)

print(ar7)

print(ar7.shape)

ar7.dtype

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)


dtype('int32')

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:
# Solution
cent = np.diagonal(ar7)
centre = cent[2]
centre

3

## 10. Print the all the elements of 3rd row of the matrix

In [11]:
# Solution
row_3 = ar7[2:3]
row_3


array([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
# Solution
col_4 = ar7[:,3]
col_4


array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [13]:
# Solution
n = len(ar7)
m = len(ar7[0])
print("left top corner :",ar7[0][0])
print("right top corner :",ar7[0][m - 1])
print("left bottom corner :",ar7[n - 1][0])
print("right bottom corner :",ar7[n - 1][m - 1])



left top corner : 9
right top corner : 45
left bottom corner : 23
right bottom corner : 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [14]:
# Solution 
m1 = ar7[0:2,2:4]
m2 = ar7[3:,0:2]
m3 = ar7[2:,2:]
print('m1 = ',m1)
print('m2 = ',m2)
print('m3 = ',m3)

m1 =  [[50 34]
 [34 65]]
m2 =  [[ 7  8]
 [23 12]]
m3 =  [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [15]:
# Solution
mr1 = m1.flatten()
mr2 = m2.flatten()
mr3 = m3.flatten()
print(mr1)
print(mr2)
print(mr3)

[50 34 34 65]
[ 7  8 23 12]
[ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [16]:
# Solution
con_ver = np.concatenate((m1,m2),axis = 1)
print(con_ver)
#m_1 = m1.reshape(1,4)
#m_2 = m2.reshape(1,4)
con_hor = np.concatenate((m1,m2),axis = 0)
print(con_hor)

[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [17]:
# Solution
add = m1+m2
multiply = m1*m2
divide = m1/m2
print(add)
print(multiply)
print(divide)

[[57 42]
 [57 77]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [18]:
# Solution
mre3 = np.delete(m3,0,0)
mce3 = np.delete(mre3,-1,-1)
print(mre3)
print(mce3)
add_1 = m1 + m2
add_1

[[ 6 54  6]
 [ 8  5  8]]
[[ 6 54]
 [ 8  5]]


array([[57, 42],
       [57, 77]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [19]:
# Solution
me1 = m1.mean(axis=0) #for row axis =1
me2 = m2.mean(axis=0) 



#### 19. Perform the matrix multiplication between m3 and m4

In [20]:
# Solution




#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [21]:
# Solution
print(ar7)
row1 = (ar7[0:1]).mean()
row2 = (ar7[1:2]).mean()
row3 = (ar7[2:3]).mean()
row4 = (ar7[3:4]).mean()
row5 = (ar7[4:]).mean()
print('mean of row1:', row1)
print('mean of row1:', row1)
print('mean of row1:', row1)
print('mean of row1:', row1)
print('mean of row1:', row1)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
mean of row1: 32.6
mean of row1: 32.6
mean of row1: 32.6
mean of row1: 32.6
mean of row1: 32.6


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [22]:
# Solution 
#MSD
MSD_Runs = np.array([54,60,10,65])
MSD_Balls = np.array([50,42,22,78])
MSD_A = MSD_Runs/len(MSD_Runs)
MSD_S = (MSD_Runs/MSD_Balls)*100
MSD_Avg = np.sort(MSD_A)[::-1]
MSD_SR = np.sort(MSD_S)[::-1]

#Kholi
Kholi_Runs = np.array([102,2,78,32])
Kholi_Balls = np.array([95,8,65,43])
Kholi_A = Kholi_Runs/len(Kholi_Runs)
Kholi_S = (Kholi_Runs/Kholi_Balls)*100
Kholi_Avg = np.sort(Kholi_A)[::-1]
Kholi_SR = np.sort(Kholi_S)[::-1]

#Rohit
Rohit_Runs = np.array([3,110,1,92])
Rohit_Balls = np.array([9,100,7,101])
Rohit_A = Rohit_Runs/len(Rohit_Runs)
Rohit_S = (Rohit_Runs/Rohit_Balls)*100
Rohit_Avg = np.sort(Rohit_A)[::-1]
Rohit_SR = np.sort(Rohit_S)[::-1]

#Rahul
Rahul_Runs = np.array([56,6,12,42])
Rahul_Balls = np.array([27,3,11,31])
Rahul_A = Rahul_Runs/len(Rahul_Runs)
Rahul_S = (Rahul_Runs/Rahul_Balls)*100
Rahul_Avg = np.sort(Rahul_A)[::-1]
Rahul_SR = np.sort(Rahul_S)[::-1]

#Dhawan
Dhawan_Runs = np.array([12,8,22,11])
Dhawan_Balls = np.array([24,20,36,27])
Dhawan_A = Dhawan_Runs/len(Dhawan_Runs)
Dhawan_S = (Dhawan_Runs/Dhawan_Balls)*100
Dhawan_Avg = np.sort(Dhawan_A)[::-1]
Dhawan_SR = np.sort(Dhawan_S)[::-1]

#Average
Average = np.concatenate((MSD_Avg.reshape(1,4),Kholi_Avg.reshape(1,4),Rohit_Avg.reshape(1,4),Rahul_Avg.reshape(1,4),Dhawan_Avg.reshape(1,4)),axis=0)

#Strike Rate
Strike_Rate = np.concatenate((MSD_SR.reshape(1,4),Kholi_SR.reshape(1,4),Rohit_SR.reshape(1,4),Rahul_SR.reshape(1,4),Dhawan_SR.reshape(1,4)),axis=0)

print('The Average is:', Average)
print('The Strike Rate is:', Strike_Rate)

The Average is: [[16.25 15.   13.5   2.5 ]
 [25.5  19.5   8.    0.5 ]
 [27.5  23.    0.75  0.25]
 [14.   10.5   3.    1.5 ]
 [ 5.5   3.    2.75  2.  ]]
The Strike Rate is: [[142.85714286 108.          83.33333333  45.45454545]
 [120.         107.36842105  74.41860465  25.        ]
 [110.          91.08910891  33.33333333  14.28571429]
 [207.40740741 200.         135.48387097 109.09090909]
 [ 61.11111111  50.          40.74074074  40.        ]]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [23]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
p = marks[:]>50
f = marks[:]<50
print('Number of Students Passed:', np.count_nonzero(p))
print('Number of Students Failed:', np.count_nonzero(f))

Number of Students Passed: 7
Number of Students Failed: 3


23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [24]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,39])
for i in range(0,len(marks)):
    if(((marks[i]>45)&(marks[i]<49))|(marks[i]>80)):
        marks[i]=marks[i]+5
        if marks[i]>=100:
            marks[i]=100
            
print("new array after mercy marks:\n",marks)
print("\nTotal Number of students is",len(marks),"Passed nos:",((marks>50).sum()),"false")
new_pass_percent = (((marks>50).sum())/len(marks))*100
print("New Pass Percentage", new_pass_percent,'%')
print("Difference in percentage is", new_pass_percent-marks,"%")


new array after mercy marks:
 [ 65  89  52  56  94 100  53  77  39]

Total Number of students is 9 Passed nos: 8 false
New Pass Percentage 88.88888888888889 %
Difference in percentage is [ 23.88888889  -0.11111111  36.88888889  32.88888889  -5.11111111
 -11.11111111  35.88888889  11.88888889  49.88888889] %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [25]:
# Solution
import time
def lst():
    x = list(range(1,60000))
    y = list(range(1,60000))
    res=[]
    for i in range(len(x)):
        res.append((((x[i]**2)+8)/y[i]))
        #print(res)

def npy():
    x = np.array(range(1,60000))
    y = np.array(range(1,60000))
    res = ((x**2)+8)/y
    #print(res)

start = time.time()
%time lst()
end = time.time()
print('The Time taken for list is:', end-start)
start1 = time.time()
%time npy()
end1 = time.time()
print('The Time taken for npy is:', end1-start1)

Wall time: 35.9 ms
The Time taken for list is: 0.03690052032470703
Wall time: 12 ms
The Time taken for npy is: 0.013963460922241211


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [26]:
# Solution



